[nbd]
network_buffer_size = 8192
verbosity = "info"

[kafka]
broker = "192.168.1.23:9092"
timeout = 6000
retries = 2

[[provider]]
topic = "provider.first"
group = "230.44.4.2"
port = 5700
message_size = 1024
interface = "0.0.0.0"

[[provider]]
topic = "provider.second"
group = "230.2.4.2"
port = 5710
message_size = 2048
interface = "0.0.0.0"

[[provider]]
topic = "provider.third"
group = "230.44.45.2"
port = 5720
message_size = 1024
interface = "0.0.0.0"
