mod commons;
#[cfg(windows)]
use commons::NtSetTimerResolution;
use commons::show_report;

use nothing_but_data::{IPerfSink, Interface, Provider, ProviderConfig};

#[cfg(feature = "metrics-exporter")]
use std::net::{IpAddr, Ipv4Addr};
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};

use tokio_util::sync::CancellationToken;

#[cfg(feature = "metrics-exporter")]
use metrics_exporter_prometheus::PrometheusBuilder;

#[cfg(windows)]
const WINDOWS_TIMER_TESTING_RESOLUTION_MS: f32 = 0.005;

const STRESS_TEST_DURATION_SECONDS: u64 = 5 * 60;
const STRESS_TEST_CHANNEL_COUNT: usize = 5;

/// This test aims at testing NBD's internal handling of a continuous network flow from multiple producers.
/// In this test, the network flow is externally generated by iperf packets (necessary as they are decoded by the IPerfSink).
/// It doesn't take into consideration the transaction time with a Kafka broker (this is dealt with in the "e2e_multi_channel_stress" test).

#[tokio::test]
async fn multi_channel_stress_test() {
    #[cfg(feature = "metrics-exporter")]
    match PrometheusBuilder::new()
        .with_http_listener((IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), 9000))
        .set_buckets_for_metric(
            "nbd_e2e_latency",
            &[0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 1],
        )
        .install()
    {
        Ok(_) => {
            println!("Prometheus metrics exporter started at http://127.0.0.1:9000",);
        }
        Err(e) => {
            println!(
                "Failed to start Prometheus metrics exporter on http://http://127.0.0.1:9000 : {}",
                e,
            );
        }
    };

    println!(
        "Stress test will be running for {} seconds.",
        STRESS_TEST_DURATION_SECONDS
    );

    let tx_count = Arc::new(AtomicU64::new(0));

    #[cfg(windows)]
    let mut timer_resolution_change = false;

    #[cfg(windows)]
    let mut actual_100ns = 0;

    #[cfg(windows)]
    unsafe {
        let res = NtSetTimerResolution(
            (WINDOWS_TIMER_TESTING_RESOLUTION_MS * 10_000.0) as u32,
            1,
            &mut actual_100ns,
        );

        if res == 0 {
            println!(
                "Successfully reduced Windows' timer resolution to {} ms.",
                (actual_100ns as f32) / 10_000.0
            );
            timer_resolution_change = true;
        } else {
            println!("Failed to reduce Windows' timer resolution. Default is at 15,6ms.");
        }
    }

    let token = CancellationToken::new();
    let mut test_sinks: Vec<IPerfSink> = Vec::new();

    for i in 1..(STRESS_TEST_CHANNEL_COUNT + 1) {
        let config_test = ProviderConfig {
            topic: "test".to_string(),
            group: format!("239.255.0.{i}").parse().unwrap(),
            port: 20_000 + i as u16,
            message_size: 2048,
            interface: Interface::V4(std::net::Ipv4Addr::UNSPECIFIED),
        };

        let mut provider = Provider::from(&config_test);
        provider.subscribe(&(250 * 1024 * 1024)).unwrap();

        let port = match provider.get_socket() {
            Ok(ref socket) => match socket.local_addr() {
                Ok(sockaddr) => match sockaddr.as_socket() {
                    Some(socketaddr) => socketaddr.port(),
                    None => 0,
                },
                Err(_) => 0,
            },
            Err(_) => 0,
        };

        assert_ne!(port, 0);

        let listener_token = token.clone();
        let listener_sink = IPerfSink::default();

        let task_sink = listener_sink.clone();

        tokio::spawn(async move { provider.start_listener(task_sink, listener_token).await });

        test_sinks.push(listener_sink);

        println!("Spawned a listener on : 239.255.0.{i}:{port}");
    }

    tokio::time::sleep(std::time::Duration::from_secs(STRESS_TEST_DURATION_SECONDS)).await;
    token.cancel();

    let total_received_bytes: u64 = test_sinks
        .clone()
        .into_iter()
        .map(|s| s.received_bytes.load(Ordering::Relaxed))
        .sum::<usize>() as u64;

    let total_received_messages: u64 = test_sinks
        .clone()
        .into_iter()
        .map(|s| s.received_messages.load(Ordering::Relaxed))
        .sum::<u64>() as u64;

    let latencies = test_sinks
        .clone()
        .into_iter()
        .flat_map(|s| s.state.lock().unwrap().latencies.to_vec())
        .collect();

    show_report(
        &format!(
            "{}-seconds-multi-iperf-stress-test",
            STRESS_TEST_DURATION_SECONDS
        ),
        latencies,
        Some(tx_count.load(Ordering::Relaxed)),
        Some(total_received_messages),
    );

    println!(
        "Processed a total of {} bytes in {} secs. ({} bytes/s)\n",
        total_received_bytes,
        STRESS_TEST_DURATION_SECONDS,
        total_received_bytes / STRESS_TEST_DURATION_SECONDS
    );

    let pkt_indexes = test_sinks
        .clone()
        .into_iter()
        .map(|s| s.state.lock().unwrap().indexes.to_vec());

    for (idx, pkt_index) in pkt_indexes.enumerate() {
        if pkt_index.is_empty() {
            continue;
        }

        let nb_received = pkt_index.len();
        let min_seq = *pkt_index.first().unwrap();
        let max_seq = *pkt_index.iter().max().unwrap();

        let mut nb_disorderly = 0usize;
        let mut highest_seq_seen = 0u32;

        for &seq in &pkt_index {
            if seq < highest_seq_seen {
                nb_disorderly += 1;
            } else {
                highest_seq_seen = seq;
            }
        }

        let total_expected = (max_seq - min_seq + 1) as usize;
        let nb_missing = total_expected.saturating_sub(nb_received);

        let accuracy_pct = (nb_received as f64 / total_expected as f64) * 100.0;
        let order_pct = ((nb_received - nb_disorderly) as f64 / nb_received as f64) * 100.0;

        let title = format!(" Sink n° {} statistics ", idx);
        let accuracy_line = format!(
            "Accuracy : {:>6.2}% ({} missing / {} expected)",
            accuracy_pct, nb_missing, total_expected
        );
        let order_line = format!(
            "Order    : {:>6.2}% ({} misordered / {} received)",
            order_pct, nb_disorderly, nb_received
        );

        let content_width = accuracy_line
            .chars()
            .count()
            .max(order_line.chars().count())
            .max(title.chars().count() + 2);

        println!(
            "╔═{}═{}╗",
            title,
            "═".repeat(content_width - title.chars().count())
        );
        println!("║ {: <width$} ║", accuracy_line, width = content_width);
        println!("║ {: <width$} ║", order_line, width = content_width);
        println!("╚{}╝", "═".repeat(content_width + 2));
    }

    #[cfg(windows)]
    unsafe {
        if timer_resolution_change {
            if NtSetTimerResolution(5_000, 0, &mut actual_100ns) == 0 {
                println!("Successfully restored Windows' timer resolution.");
            } else {
                println!("Failed to restore Windows' timer resolution.");
            }
        };
    }
}
