name: Audit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format check
      run: cargo fmt -- --check
    - name: Cargo check
      run: cargo check --all-features
    - name: Add auditing/building tools
      run: |
        cargo install cargo-audit cargo-outdated cargo-deny
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libsasl2-dev
        rustup component add clippy
    - name: Version check
      run: cargo outdated
    - name: Audit check
      run: cargo audit
    - name: Clippy check
      run: cargo clippy -- -D warnings
    - name: Deny check
      run: cargo deny check
    - name: Build
      run: cargo build
