name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt
    - name: Update
      run: cargo update
    - name: Add auditing tools
      run: cargo install cargo-audit cargo-outdated
    - run: rustup component add clippy
    - name: Check
      run: cargo outdated
    - name: Audit
      run: cargo audit
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build
